build: 'off'
environment:
  matrix:
    - nodejs_version: '12'
    - nodejs_version: '14'
install:
  - ps: 'Install-Product node $env:nodejs_version x64'
  - npm ci
test_script:
  - node --version
  - npm --version
  - npm install -g .
  - npm test
